### ISSUE TITLE
请问我在运性训练脚本的时候，有以下报错，我去看了huggingface的官方文档，最新的文档中evaluation strategy和save strategy还是no,epoch,steps

### ISSUE THREAD

**Issue by kkkeepgoing** [RunxinXu/TSAR#13]
Traceback (most recent call last):
  File "/data/hmzhong/TSAR/code/run.py", line 747, in <module>
    main()
  File "/data/hmzhong/TSAR/code/run.py", line 165, in main
    model_args, data_args, training_args = parser.parse_args_into_dataclasses()
  File "/home/hmzhong/anaconda3/envs/xs/lib/python3.9/site-packages/transformers/hf_argparser.py", line 332, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 110, in __init__
  File "/home/hmzhong/anaconda3/envs/xs/lib/python3.9/site-packages/transformers/training_args.py", line 1180, in __post_init__
    raise ValueError(
ValueError: --load_best_model_at_end requires the save and eval strategy to match, but found
- Evaluation strategy: epoch
- Save strategy: steps

**Comment by xiehou-design** [comment]
install transformers==4.8.1 can solve this problem
