### ISSUE TITLE
How to get the AMR result of the RAMS dataset

### ISSUE THREAD

**Issue by XxscXie** [RunxinXu/TSAR#6]
Hi @RunxinXu,

It seems that amrparse.py takes the transferred RAMS dataset as the input, which is similar to the WikiEvent dataset. However, there's no script for transferring the RAMS dataset. I tried to use the original RAMS dataset as the input of amrparse.py. but it seems that some sentences are too long, which causes an IndexError. Here's the detail of the error

Traceback (most recent call last):
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/parser/amrparse.py", line 42, in <module>
    parse_rams(parser, split)
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/parser/amrparse.py", line 17, in parse_rams
    amr_list = parser.parse_sentences(all_sentences)
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/transition_amr_parser/stack_transformer_amr_parser.py", line 422, in parse_sentences
    roberta_batch_size)
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/transition_amr_parser/stack_transformer_amr_parser.py", line 297, in convert_sentences_to_data
    self.get_bert_features_batched(sentences, roberta_batch_size)
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/transition_amr_parser/stack_transformer_amr_parser.py", line 270, in get_bert_features_batched
    batch_data = self.embeddings.extract_batch(batch)
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/transition_amr_parser/stack_transformer/pretrained_embeddings.py", line 310, in extract_batch
    word_features = get_average_embeddings(roberta_features.unsqueeze(0), word2piece)
  File "/home/kxie/dh39/kyxie/transition-amr-parser-master/transition_amr_parser/stack_transformer/pretrained_embeddings.py", line 21, in get_average_embeddings
    column = final_layer[0:1, wordpiece_idx, :]
IndexError: index 510 is out of bounds for dimension 0 with size 510

In terms of getting the AMR result of the original RAMS dataset, do you have any suggestions?

**Comment by RunxinXu** [comment]
It seems like an error occurred in the transition_amr_parser.
Do you use the right version?

**Comment by XxscXie** [comment]
> It seems like an error occurred in the transition_amr_parser. Do you use the right version?

@RunxinXu 
Thanks for your reply. The transition_amr_parser I used was provided by https://github.com/zhangzx-uiuc/AMR-IE. I downloaded the code from the drive and installed it locally. The version number is 0.3.3rc0.

**Comment by RunxinXu** [comment]
with torch==1.6.0 ?

**Comment by XxscXie** [comment]
> with torch==1.6.0 ?

I was using torch 1.7.0+cu110. This is because torch 1.6.0 returns the error below: 
- NVIDIA A40 with CUDA capability sm_86 is not compatible with the current PyTorch installation.

It seems that sm_86 architecture doesn't support torch 1.6.0+cu101. The solution I found (https://github.com/pytorch/pytorch/issues/45028#issuecomment-695250988) also mentioned that torch 1.7.0 should be used on sm_86 architecture

Does the AMR parser only work on torch 1.6.0?

**Comment by RunxinXu** [comment]
I did not try to run it with torch 1.7.0+cu110.
I try my best to keep consistent with the configs in [https://github.com/zhangzx-uiuc/AMR-IE](https://github.com/zhangzx-uiuc/AMR-IE).
So maybe this is the reason why the error occurs, I gauss?

**Comment by XxscXie** [comment]
> So maybe this is the reason why the error occurs, I gauss?

Thanks for your suggestion. I downgraded PyTorch to 1.6.0 and tried to feed the train/test/dev.jsonlines from RAMS to amrparser.py, but it returned the same error. I noticed that the transfer.py would keep the context from WikiEvent less than 400 tokens. Should the same algorithm be applied to RAMS dataset to make the context shorter?

**Comment by crawlerWPS** [comment]
I also noticed similar errors. It seems that the "rams" folder is missing a file like "transfer.py" found in the "wikievents" folder.
